#!/bin/bash

function component {
   cd ${prefix}/share/iCub/contexts/simConfig
   CMD=${prefix}/bin/iCub_SIM
   $CMD
}

function clean_component {
    true
}

function on_check {
    yarp ping /icubSim/face/eyelids 2>/dev/null  > /dev/null
}

function on_start {
    true
}

function on_stop {
    true
}

function stop_component {
    local PIDS=$(all_children $(vdemo_pidFromScreen $1))
    echo "killing processes $PIDS"
    kill -SIGINT $PIDS > /dev/null 2>&1
    sleep .5
    kill -SIGTERM $PIDS > /dev/null 2>&1
    for i in {1..50}; do
        sleep 0.1
        kill -0 $PIDS > /dev/null 2>&1 || break
    done
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
