#!/bin/bash

function component {
   hlrc_test_gui ROS $BASE_SCOPE
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
