#!/bin/bash

function component {
  mary_tts_provider $BASE_SCOPE/tts_provider
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
