#!/bin/bash

function component {
  hlrc_server ROS ROS $BASE_SCOPE $SOUND_OUTPUT
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
