#!/bin/bash

function component {
  ${prefix}/share/hai16-demo/hlrc_demo_animation.py
}

function clean_component {
    true
}

function on_start {
    true
}

function on_stop {
    true
}

source "$VDEMO_root/vdemo_standard_component_suffix.sh"
